import { JobProps } from "../interfaces";

export const JOBSLISTINGSAMPLE: JobProps[] = [
    {
      id: "1",
      title: "Frontend Developer",
      category: "Software Engineering",
      location: "Kigali, Rwanda",
      experience: "Mid-Level",
      company: "Tech Innovators Ltd",
    },
    {
      id: "2",
      title: "Backend Developer",
      category: "Software Engineering",
      location: "New York, USA",
      experience: "Senior",
      company: "Global Softwares Inc.",
    },
    {
      id: "3",
      title: "UI/UX Designer",
      category: "Design",
      location: "London, UK",
      experience: "Entry-Level",
      company: "Creative Minds Studio",
    },
    {
      id: "4",
      title: "Data Analyst",
      category: "Data Science",
      location: "Berlin, Germany",
      experience: "Mid-Level",
      company: "DataTech Solutions",
    },
    {
      id: "5",
      title: "Project Manager",
      category: "Management",
      location: "San Francisco, USA",
      experience: "Senior",
      company: "InnovateX",
    },
    {
      id: "6",
      title: "Full Stack Developer",
      category: "Software Engineering",
      location: "Musanze, Rwanda",
      experience: "Mid-Level",
      company: "Rwanda IT Hub",
    },
    {
      id: "7",
      title: "Marketing Specialist",
      category: "Marketing",
      location: "Toronto, Canada",
      experience: "Entry-Level",
      company: "BrandBoost Agency",
    },
    {
      id: "8",
      title: "Cybersecurity Analyst",
      category: "Cybersecurity",
      location: "Sydney, Australia",
      experience: "Senior",
      company: "SecureNet Solutions",
    },
    {
      id: "9",
      title: "Product Manager",
      category: "Product Management",
      location: "Amsterdam, Netherlands",
      experience: "Mid-Level",
      company: "GrowthTech",
    },
    {
      id: "10",
      title: "DevOps Engineer",
      category: "Software Engineering",
      location: "Kigali, Rwanda",
      experience: "Senior",
      company: "SmartCloud Ltd",
    },
    {
      id: "11",
      title: "Software Engineer",
      category: "Software Engineering",
      location: "Butare, Rwanda",
      experience: "Entry-Level",
      company: "NextGen Developers",
    },
    {
      id: "12",
      title: "Business Analyst",
      category: "Business",
      location: "Gisenyi, Rwanda",
      experience: "Mid-Level",
      company: "BizSolutions Ltd",
    },
    {
      id: "13",
      title: "HR Manager",
      category: "Human Resources",
      location: "Kigali, Rwanda",
      experience: "Senior",
      company: "PeopleFirst HR",
    },
    {
      id: "14",
      title: "Network Engineer",
      category: "IT & Networking",
      location: "Huye, Rwanda",
      experience: "Mid-Level",
      company: "ConnectIT Ltd",
    },
    {
      id: "15",
      title: "AI/ML Engineer",
      category: "Artificial Intelligence",
      location: "Nairobi, Kenya",
      experience: "Senior",
      company: "AI Innovators",
    },
    {
      id: "16",
      title: "Social Media Manager",
      category: "Marketing",
      location: "Rubavu, Rwanda",
      experience: "Entry-Level",
      company: "DigitalWave Media",
    },
    {
      id: "17",
      title: "Finance Officer",
      category: "Finance",
      location: "Kigali, Rwanda",
      experience: "Mid-Level",
      company: "FinTrust Ltd",
    },
    {
      id: "18",
      title: "Android Developer",
      category: "Software Engineering",
      location: "Johannesburg, South Africa",
      experience: "Mid-Level",
      company: "AppWorks SA",
    },
    {
      id: "19",
      title: "Customer Support Representative",
      category: "Customer Service",
      location: "Kigali, Rwanda",
      experience: "Entry-Level",
      company: "HelpDesk Rwanda",
    },
    {
      id: "20",
      title: "Blockchain Developer",
      category: "Blockchain",
      location: "San Francisco, USA",
      experience: "Senior",
      company: "CryptoTech Solutions",
    },
    {
      id: "21",
      title: "Graphic Designer",
      category: "Design",
      location: "Huye, Rwanda",
      experience: "Entry-Level",
      company: "PixelArt Studio",
    },
    {
      id: "22",
      title: "AI Research Scientist",
      category: "Artificial Intelligence",
      location: "Paris, France",
      experience: "Senior",
      company: "DeepMind Research",
    },
    {
      id: "23",
      title: "Data Engineer",
      category: "Data Science",
      location: "Tokyo, Japan",
      experience: "Mid-Level",
      company: "BigData Analytics",
    },
    {
      id: "24",
      title: "QA Tester",
      category: "Quality Assurance",
      location: "Kigali, Rwanda",
      experience: "Entry-Level",
      company: "TestMaster Ltd",
    },
    {
      id: "25",
      title: "Technical Writer",
      category: "Content Writing",
      location: "Musanze, Rwanda",
      experience: "Mid-Level",
      company: "TechDocs Africa",
    },
  ];
  